# Lab 4.1.3 Abbe refractometer

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
data1=genfromtxt("скользящий.csv",delimiter=",",skip_header=1)
cn=.5e-3
len(data1)

5

In [3]:
n1=mean(data1,axis=0)
sn1=sqrt(std(data1,axis=0)**2+cn**2)/2
print(n1,sn1)

[ 1.3182  1.3469  1.6224  1.6223  1.6216  1.4578] [ 0.00035707  0.00038406  0.00056789  0.00027839  0.00058949  0.00055   ]


In [4]:
data2=genfromtxt("отражение.csv",delimiter=',',skip_header=1)

In [5]:
n2=mean(data2,axis=0)
sn2=sqrt(std(data2,axis=0)**2+cn**2)/2
print(n2,sn2)

[ 1.3167  1.3459  1.619   1.5986  1.456 ] [ 0.00035707  0.00066895  0.00075     0.00308585  0.00075   ]


In [8]:
ns=hstack((n1[:2],n1[-1:]))
sns=hstack((sn1[:2],sn1[-1:]))

In [9]:
no=hstack((n2[:2],n2[-1:]))
sno=hstack((sn2[:2],sn2[-1:]))

In [14]:
M=array((18,46,92))
sM=0.1
rho=array((1,0.79,1.26))
srho=1e-3

In [15]:
RMs=M/rho*(ns**2-1)/(ns**2+2)
sRMs=RMs*sqrt((sM/M)**2+(srho/rho)**2+(6*ns*sns/(ns**2+2))**2)
print(RMs,sRMs)

[  3.55242409  12.4289099   19.91574782] [ 0.02023171  0.0328612   0.03546654]


In [16]:
RMo=M/rho*(no**2-1)/(no**2+2)
sRMo=RMs*sqrt((sM/M)**2+(srho/rho)**2+(6*no*sno/(no**2+2))**2)
print(RMo,sRMo)

[  3.53713045  12.39655279  19.84814928] [ 0.02023168  0.03588712  0.04149202]


In [17]:
NA=6.02e23
alphas=RMs*3/(4*pi*NA)
salphas=sRMs*3/(4*pi*NA)
print(alphas,salphas)

[  1.40876874e-24   4.92887653e-24   7.89789795e-24] [  8.02319719e-27   1.30316169e-26   1.40648071e-26]


In [18]:
alphao=RMo*3/(4*pi*NA)
salphao=sRMo*3/(4*pi*NA)
print(alphao,salphao)

[  1.40270381e-24   4.91604482e-24   7.87109070e-24] [  8.02318582e-27   1.42315939e-26   1.64543012e-26]


In [23]:
RM=RMs
sRM=sRMs

In [24]:
R_O=1/2*RM[2]-3/4*RM[1]+1/4*RM[0]
R_H=-1/4*RM[2]+3/8*RM[1]+3/8*RM[0]
R_C=1/2*RM[2]-1/4*RM[1]-5/4*RM[0]
print(R_O,R_H,R_C)

1.52429751279 1.01406329061 2.41011631988


In [25]:
sR_O=sqrt((1/2*sRM[2])**2+(3/4*sRM[1])**2+(1/4*sRM[0])**2)
sR_H=sqrt((1/4*sRM[2])**2+(3/8*sRM[1])**2+(3/8*sRM[0])**2)
sR_C=sqrt((1/2*sRM[2])**2+(1/4*sRM[1])**2+(5/4*sRM[0])**2)
print(sR_O,sR_H,sR_C)

0.0307810319312 0.0169715419789 0.0319613171309


In [26]:
R_CH4O=R_C+4*R_H+R_O
sR_CH4O=sqrt(sR_C**2+16*sR_H**2+sR_O**2)
print(R_CH4O,sR_CH4O)

7.99066699512 0.0811019698514


In [29]:
rho_CH4O=.79
M_CH4O=32
n_CH4O=sqrt(3/(1-R_CH4O*rho_CH4O/M_CH4O)-2)
sn_CH4O=sR_CH4O*rho_CH4O/M_CH4O*3/(1-R_CH4O*rho_CH4O/M_CH4O)**2/(3/(1-R_CH4O*rho_CH4O/M_CH4O)-2)/2*n_CH4O
print(n_CH4O,sn_CH4O)

1.31804580486 0.0035361431814


In [30]:
R_ice,sR_ice=RM[0],sRM[0]
rho_ice,M_ice=.917,18
n_ice=sqrt(3/(1-R_ice*rho_ice/M_ice)-2)
sn_ice=sR_ice*rho_ice/M_ice*3/(1-R_ice*rho_ice/M_ice)**2/(3/(1-R_ice*rho_ice/M_ice)-2)/2*n_ice
print(n_ice,sn_ice)

1.28953384655 0.00178728966045


In [32]:
rho_C,M_C=3.5,12
n_C=sqrt(3/(1-R_C*rho_C/M_C)-2)
sn_C=sR_C*rho_C/M_C*3/(1-R_C*rho_C/M_C)**2/(3/(1-R_C*rho_C/M_C)-2)/2*n_C
print(n_C,sn_C)

2.84593219383 0.0556827657697
